version: "1.0"
services:
  postgres:
    image: postgres:14
    volumes:
      - /data/security-simple/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: security_simple_pwd
      PGDATA: /var/lib/postgresql/data

  redis:
    image: redis
    volumes:
      - /data/security-simple/redis:/data

  web:
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - 8080:8080