spring:
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/security_db
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
      database: 0