spring:
  datasource:
    driver-class-name: com.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_mp
    username: postgres
    password: postgres
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_active
      logic-delete-value: 0
      logic-not-delete-value: 1