spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_endpoint
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: ""
      lettuce:
        pool:
          min-idle: 2
          max-active: 2

  jackson:
    date-format: yyyy-MM-dd HH:MM:SS
    default-property-inclusion: non_null

mxzero:
  security:
    jwt:
      issuer: oauth.mxzero.top
      secret: jwt-dev
      expire: 7200
      refresh: 86400
