spring:
  #  datasource:
  #    driver-class-name: org.postgresql.Driver
  #    url: jdbc:postgresql://localhost:5432/db_endpoint
  #    username: postgres
  #    password: postgres
  shardingsphere:
    mode:
      type: Standalone
      repository:
        type: JDBC
    datasource:
      names: ds1,ds2
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/db_endpoint
        username: postgres
        password: postgres
      ds2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/db_endpoint_2
        username: postgres
        password: postgres
    rules:
      sharding:
        tables:
          t_message:
            actualDataNodes: ds$->{1..2}.t_message
            tableStrategy:
              none: # 表不分片，表名一致
        default-database-strategy:
          standard:
            sharding-column: id
            shardingAlgorithmName: database-inline
        shardingAlgorithms:
          database-inline:
            type: INLINE
            props:
              algorithm-expression: "ds$->{id % 2 == 0 ? 1 : 2 }"
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: helloredis
      lettuce:
        pool:
          min-idle: 2
          max-active: 2
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8:00


mxzero:
  security:
    jwt:
      issuer: oauth.mxzero.top
      secret: jwt-dev
      expire: 7200
      refresh: 86400
